#!/usr/bin/env python3
"""
Maintenance script (not part of the published block) -- regenerates shapes.shacl
from the live W3C PROV-O ontology.

Requires: rdflib (`pip install rdflib`)
Run from this directory:  python3 generate-shapes.py

What it does
------------
This is the strict counterpart to ../prov/generate-shapes.py. Where the base PROV
block's shapes only require an explicit `sh:class` when an object-property value is
given as a blank node (see that script's docstring for the open-world rationale), this
script emits one PropertyShape per PROV-O *object* property requiring `sh:class` on
its value whenever that value is actually *described* in the graph -- i.e. it appears
as the subject of at least one triple, blank node or IRI alike. A value that is a pure
by-reference pointer (no outgoing triples of its own in this graph) is not required to
carry a type: nothing in this graph could assert one, so demanding it would reject
valid, genuinely external references. A value that *is* described here but left
untyped is a real omission and is rejected.

Concretely, each property's constraint is `sh:or` between:
  - `sh:class <range>` (or an alternative per range class, if there's more than one)
  - `<#NotDescribedInGraph>`, a single shared shape (defined once, referenced by every
    property shape below -- not repeated) that holds for a node exactly when it has no
    outgoing triples, via a `sh:sparql` constraint.

Running this block's `entail` transform (../prov/transforms.yaml) against the base
PROV block's own RDFS domain/range axioms still matters: entailment types *every*
value of a PROV object property from the triggering property assertion alone,
regardless of whether that value is otherwise described here, so it is the only way
to satisfy the strict `sh:class` alternative for a value this graph doesn't otherwise
describe (rather than falling back to the `<#NotDescribedInGraph>` alternative for it).

Each shape targets every subject of the property in question (`sh:targetSubjectsOf`)
rather than re-deriving PROV-O's class hierarchy the way the base block's node shapes
do -- so this file adds its constraints without repeating the domain-class ->
property-list associations already expressed in ../prov/shapes.shacl (inherited
automatically at validation time via this block's `dependsOn`).

Datatype properties are out of scope here: this block only tightens *object*-valued
properties (the ones affected by the by-reference-typing relaxation); literal-valued
properties are validated identically in both blocks and are left to the base block's
shapes so they are not duplicated.

Output: overwrites shapes.shacl in this directory. Re-run whenever PROV-O itself is
revised; do not hand-edit the generated shapes below the header comment (hand edits
will be lost on the next run).
"""
import urllib.request

import rdflib
from rdflib import OWL, RDFS, RDF
from rdflib.collection import Collection

PROV_O_URL = "https://www.w3.org/ns/prov-o#"
LOCAL_CACHE = "prov-o.ttl"

HEADER = """# Strict SHACL shapes for the W3C PROV-O ontology (http://www.w3.org/ns/prov#),
# mechanically derived from PROV-O's OWL axioms (rdfs:range per object property).
#
# Generated by generate-shapes.py in this directory -- see that script's module
# docstring for the full rationale. Do not hand-edit below this header; re-run the
# script instead.
#
# This is the strict counterpart to ../prov/shapes.shacl (this block's dependsOn):
# where that file only requires sh:class when a value is given as a blank node, this
# file requires it for every value actually *described* in the graph (has at least one
# outgoing triple) -- blank node or by-reference IRI alike. A value with no outgoing
# triples at all is a pure external reference this graph could not type even in
# principle, so it is exempt (see <#NotDescribedInGraph> below) rather than rejected.
# Running the base block's `entail` transform (../prov/transforms.yaml) first still
# matters: it types every PROV object-property value from the property assertion
# itself, regardless of local description, which is the only way an undescribed value
# can satisfy the sh:class alternative instead of merely falling back to the
# <#NotDescribedInGraph> exemption.
#
# Each shape below targets every subject of the property in question
# (sh:targetSubjectsOf) instead of restating PROV-O's class hierarchy and
# domain-to-property associations, which are already expressed by ../prov/shapes.shacl
# and inherited automatically at validation time via dependsOn -- so nothing here
# duplicates that file. Datatype (literal-valued) properties are unaffected by the
# typing relaxation this block addresses and are therefore left entirely to the base
# block's shapes.

@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@base <https://www.ogc.org/rules/prov/strict/> .

# Shared by every property shape below via sh:or: a node conforms to this shape
# exactly when it has no outgoing triples in the data graph, i.e. it is not itself
# described here -- only referenced. sh:sparql's SELECT reports a violation (so this
# shape does *not* hold) for any $this that has at least one outgoing triple.
<#NotDescribedInGraph>
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "Value is described in this graph and must therefore be explicitly typed." ;
        sh:select \"\"\"
            SELECT $this
            WHERE { $this ?p ?o . }
        \"\"\" ;
    ] .

"""


def fetch_ontology():
    req = urllib.request.Request(PROV_O_URL, headers={"Accept": "text/turtle"})
    with urllib.request.urlopen(req) as resp:
        data = resp.read()
    with open(LOCAL_CACHE, "wb") as f:
        f.write(data)
    return LOCAL_CACHE


def local(uri):
    return uri.split('#')[-1]


def main():
    import os
    src = LOCAL_CACHE if os.path.exists(LOCAL_CACHE) else fetch_ontology()

    g = rdflib.Graph()
    g.parse(src, format="turtle")

    def resolve(node):
        if isinstance(node, rdflib.URIRef):
            return {node}
        out = set()
        for lst in g.objects(node, OWL.unionOf):
            for member in Collection(g, lst):
                out |= resolve(member)
        return out

    all_classes = {c for c in g.subjects(RDF.type, OWL.Class) if isinstance(c, rdflib.URIRef)}
    obj_props = sorted(set(g.subjects(RDF.type, OWL.ObjectProperty)))

    shape_lines = []
    for p in obj_props:
        range_classes = set()
        for r in g.objects(p, RDFS.range):
            range_classes |= resolve(r)
        range_classes &= all_classes
        if not range_classes:
            continue

        name = local(p)
        lines = [
            f"<#prop-{name}>",
            "    a sh:PropertyShape ;",
            f"    sh:targetSubjectsOf prov:{name} ;",
            f"    sh:path prov:{name} ;",
            f"    rdfs:isDefinedBy prov:{name} ;",
        ]
        class_alts = " ".join(f"[ sh:class prov:{local(rc)} ]" for rc in sorted(range_classes))
        lines.append(f"    sh:or ( {class_alts} <#NotDescribedInGraph> ) ;")
        lines[-1] = lines[-1].rstrip(' ;') + " ."
        shape_lines.append("\n".join(lines))

    with open("shapes.shacl", "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("\n\n".join(shape_lines))
        f.write("\n")

    print(f"wrote shapes.shacl: {len(shape_lines)} property shapes")


if __name__ == "__main__":
    main()
