#!/usr/bin/env python3
"""
Maintenance script (not part of the published block) -- regenerates
shapes.shacl's OWL-derived section from the live W3C PROV-O ontology.

Requires: rdflib (`pip install rdflib`)
Run from this directory:  python3 generate-shapes.py

What it does
------------
Fetches https://www.w3.org/ns/prov-o (content-negotiated Turtle) and derives
SHACL PropertyShapes/NodeShapes from its OWL axioms, following the rule
*categories* documented by sparna-git/owl2shacl
(https://github.com/sparna-git/owl2shacl, itself an adaptation of
TopQuadrant's "From OWL to SHACL in an automated way"):

  - rdfs:domain  -> sh:property attached to the domain class's NodeShape,
                    and to every rdfs:subClassOf* descendant of that class
  - rdfs:range (object property)   -> sh:class on the PropertyShape
  - rdfs:range (datatype property) -> sh:datatype on the PropertyShape

Why not just run owl2shacl directly: its ruleset is SHACL-AF (sh:rule /
sh:SPARQLRule) and calls a TopBraid-only SPARQL extension function
(owl2sh-open:getPropertyShape) -- it only runs inside TopBraid or the
hosted SHACL Play converter (https://shacl-play.sparna.fr/play/convert),
not under an open-source engine such as pySHACL. This script re-implements
the same conversion categories directly with rdflib instead.

Deliberately NOT generated here (left to the curated, canonical shapes this
block already references via bblock.json's shaclShapes -> CDO-Shapes-PROV-O,
https://github.com/Cyber-Domain-Ontology/CDO-Shapes-PROV-O):
  - the 4 owl:disjointWith class-pairs (Activity/Entity,
    ActivityInfluence/EntityInfluence, Agent/InstantaneousEvent,
    Entity/InstantaneousEvent)
  - the 1 owl:Restriction (ActivityInfluence: maxCardinality 0 on
    prov:hadActivity)
Keeping that division avoids two shape files reporting the same violation
twice.

Output: overwrites shapes.shacl in this directory. Re-run whenever PROV-O
itself is revised; do not hand-edit the generated shapes below the header
comment (hand edits will be lost on the next run).
"""
import urllib.request

import rdflib
from rdflib import OWL, RDFS, RDF
from rdflib.collection import Collection
from rdflib.namespace import XSD

PROV_O_URL = "https://www.w3.org/ns/prov-o#"
LOCAL_CACHE = "prov-o.ttl"

HEADER = """# SHACL shapes for the W3C PROV-O ontology (http://www.w3.org/ns/prov#),
# mechanically derived from PROV-O's OWL axioms (rdfs:domain / rdfs:range
# per property, propagated down rdfs:subClassOf hierarchies).
#
# Generated by generate-shapes.py in this directory -- see that script's
# module docstring for the full rationale and the owl2shacl rule categories
# it follows. Do not hand-edit below this header; re-run the script instead.
#
# NOT covered here (left to the curated shapes this block already
# references via bblock.json's shaclShapes -> CDO-Shapes-PROV-O,
# https://github.com/Cyber-Domain-Ontology/CDO-Shapes-PROV-O):
#   - the 4 owl:disjointWith class-pairs
#   - the 1 owl:Restriction (ActivityInfluence: maxCardinality 0 on
#     prov:hadActivity)
#
# Object-property values are only sh:class-checked when given as a blank
# node (described inline). A plain-IRI value is treated as a by-reference
# pointer to an object described elsewhere and is not locally type-checked
# -- otherwise this would reject valid id-based-reference PROV-JSON-LD (see
# generate-shapes.py's docstring for the full rationale). The semantically
# correct fix -- an entailment-aware validator inferring the missing
# rdf:type from PROV-O's own rdfs:domain/rdfs:range axioms -- is not yet
# actionable: bblocks-postprocess's SHACL validator does not pass any
# `inference=` option to pySHACL, and pySHACL does not itself act on a
# shapes graph's own sh:entailment declaration (there is no such value
# declared here for that reason).

@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@base <https://www.ogc.org/rules/prov/> .

"""

XSD_TYPES = {
    XSD.dateTime, XSD.date, XSD.string, XSD.anyURI, XSD.boolean,
    XSD.integer, XSD.decimal, XSD.double, XSD.float,
}


def fetch_ontology():
    req = urllib.request.Request(PROV_O_URL, headers={"Accept": "text/turtle"})
    with urllib.request.urlopen(req) as resp:
        data = resp.read()
    with open(LOCAL_CACHE, "wb") as f:
        f.write(data)
    return LOCAL_CACHE


def local(uri):
    return uri.split('#')[-1]


def main():
    import os
    src = LOCAL_CACHE if os.path.exists(LOCAL_CACHE) else fetch_ontology()

    g = rdflib.Graph()
    g.parse(src, format="turtle")

    def resolve(node):
        """Resolve a class expression node (URIRef or owl:unionOf blank node) to named class IRIs."""
        if isinstance(node, rdflib.URIRef):
            return {node}
        out = set()
        for lst in g.objects(node, OWL.unionOf):
            for member in Collection(g, lst):
                out |= resolve(member)
        return out

    all_classes = {c for c in g.subjects(RDF.type, OWL.Class) if isinstance(c, rdflib.URIRef)}

    direct_sub = {}
    for s, o in g.subject_objects(RDFS.subClassOf):
        if isinstance(s, rdflib.URIRef) and isinstance(o, rdflib.URIRef):
            direct_sub.setdefault(o, set()).add(s)

    def descendants(c):
        seen = {c}
        stack = [c]
        while stack:
            cur = stack.pop()
            for sub in direct_sub.get(cur, ()):
                if sub not in seen:
                    seen.add(sub)
                    stack.append(sub)
        return seen

    class_props = {c: set() for c in all_classes}
    prop_shape_lines = []

    def render_property_shape(prop, is_object):
        name = local(prop)
        shape_id = f"prop-{name}"
        domain_classes = set()
        for d in g.objects(prop, RDFS.domain):
            domain_classes |= resolve(d)
        domain_classes &= all_classes

        lines = [f"<#{shape_id}>", "    a sh:PropertyShape ;", f"    sh:path prov:{name} ;",
                 f"    rdfs:isDefinedBy prov:{name} ;"]

        if is_object:
            range_classes = set()
            for r in g.objects(prop, RDFS.range):
                range_classes |= resolve(r)
            range_classes &= all_classes
            if range_classes:
                class_alts = " ".join(f"[ sh:class prov:{local(rc)} ]" for rc in sorted(range_classes))
                # Only enforce sh:class on values given as blank nodes (i.e. fully
                # described inline in the same document). A value given as a plain
                # IRI is treated as a by-reference pointer to an object described
                # elsewhere (a different document, an external registry) and is
                # not locally type-checked -- PROV-JSON-LD's id-based object graph
                # mode is a first-class, intentional usage pattern (see e.g.
                # bblock-prov-schema's examples), not an omission to flag.
                lines.append(
                    f"    sh:or ( [ sh:nodeKind sh:BlankNode ; sh:or ( {class_alts} ) ] "
                    f"[ sh:nodeKind sh:IRI ] ) ;"
                )
            else:
                lines.append("    sh:nodeKind sh:BlankNodeOrIRI ;")
        else:
            for r in g.objects(prop, RDFS.range):
                if r in XSD_TYPES:
                    lines.append(f"    sh:datatype xsd:{local(r)} ;")
                    break

        lines[-1] = lines[-1].rstrip(' ;') + " ."
        return "\n".join(lines), domain_classes

    obj_props = sorted(set(g.subjects(RDF.type, OWL.ObjectProperty)))
    data_props = sorted(set(g.subjects(RDF.type, OWL.DatatypeProperty)))

    for p in obj_props + data_props:
        is_object = p in obj_props
        text, domain_classes = render_property_shape(p, is_object)
        prop_shape_lines.append(text)
        for d in domain_classes:
            for target in descendants(d):
                class_props.setdefault(target, set()).add(f"prop-{local(p)}")

    node_shape_lines = []
    for c in sorted(all_classes, key=local):
        props = class_props.get(c, set())
        if not props:
            continue
        name = local(c)
        lines = [f"<#{name}-shape>", "    a sh:NodeShape ;", f"    sh:targetClass prov:{name} ;"]
        prop_refs = " , ".join(f"<#{p}>" for p in sorted(props))
        lines.append(f"    sh:property {prop_refs} ;")
        lines[-1] = lines[-1].rstrip(' ;') + " ."
        node_shape_lines.append("\n".join(lines))

    attached = set()
    for props in class_props.values():
        attached |= props
    prop_shape_lines = [t for t in prop_shape_lines if t.split('\n', 1)[0].strip('<#>') in attached]

    with open("shapes.shacl", "w", encoding="utf-8") as f:
        f.write(HEADER)
        f.write("\n\n".join(node_shape_lines))
        f.write("\n\n")
        f.write("\n\n".join(prop_shape_lines))
        f.write("\n")

    print(f"wrote shapes.shacl: {len(node_shape_lines)} node shapes, {len(prop_shape_lines)} property shapes")


if __name__ == "__main__":
    main()
